version: '3.1'
services:


  web:
    image: odoo:17.0

    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo:rwx
      - ./addons:/mnt/extra-addons
      - ./addons-customize:/mnt/extra-addons-customize
      

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo 
 

volumes:
  odoo-web-data:      
 
